import Head from 'next/head';
import Header from '../../organisms/Header/Header';
import styles from './Layout.module.scss';
import clsx from 'clsx';
import Footer from '@/components/organisms/Footer/Footer';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import BreadCrumbs from '@/components/molecules/BreadCrumbs/BreadCrumbs';
import { useGlobalData } from '@/hooks/useGlobalContext';
import { motion, AnimatePresence } from 'framer-motion';

function Layout({ children }) {
	const { Theme } = useGlobalData();

	const router = useRouter();
	const [Path, setPath] = useState([]);
	const [IsShow, setIsShow] = useState(true);

	useEffect(() => {
		const arr = router.asPath.split('/');
		setPath(arr);
		//router 경로가 바뀔때마다 순간적으로 IsShow값을 false로 바꿨다가
		setIsShow(false);
		//페이지 전환 모션이 끝나는 0.5초 뒤에 다시 true로 변경
		setTimeout(() => setIsShow(true), 500);
	}, [router]);

	return (
		<AnimatePresence mode='wait'>
			<motion.div key={router.pathname}>
				<Head>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<main className={clsx(styles.layout, Theme)}>
					<Header />

					<section className={clsx(styles.content)}>
						{/* 해당 BreadCrumbs의 활성화 유무를 IsShow값으로 연동 */}
						{router.asPath !== '/' && (
							<BreadCrumbs data={Path} isActive={IsShow} />
						)}
						{children}
					</section>
					<Footer />
					<motion.div
						className='in'
						initial={{ scaleX: 0 }}
						animate={{ scaleX: 0 }}
						exit={{ scaleX: 1 }}
						transition={{ duration: 0.7, ease: [0.26, 0.11, 0, 0.98] }}
					></motion.div>
					<motion.div
						className='out'
						initial={{ scaleX: 1 }}
						animate={{ scaleX: 0 }}
						exit={{ scaleX: 0 }}
						transition={{ duration: 0.7, ease: [0.26, 0.11, 0, 0.98] }}
					></motion.div>
				</main>
			</motion.div>
		</AnimatePresence>
	);
}

export default Layout;
