import Head from 'next/head';
import styles from './Home.module.scss';
import clsx from 'clsx';
import axios from 'axios';
import { Pic } from '@/components/atoms/pic/Pic';
import Title from '@/components/atoms/text/Title';
import Text from '@/components/atoms/text/Text';

export default function Home({ meals }) {
	return (
		<>
			<Head>
				<title>Next Recipe</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={clsx(styles.main)}>
				{/* 해당 요소를 활성화 시키고 싶을때에는 props으로 boolean값 전달 */}
				<Text type={'menu'} tag={'span'} isOn={true}>
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque praesentium explicabo laudantium quod iure. Nesciunt?
				</Text>
			</main>
		</>
	);
}

export async function getStaticProps() {
	//props로 데이터 넘길때에는 data안쪽의 값까지 뽑아낸다음에 전달
	const { data } = await axios.get('https://www.themealdb.com/api/json/v1/1/filter.php?c=Seafood');
	console.log('data fetching on Server', data);

	return {
		props: data,
		revalidate: 60 * 60 * 24,
	};
}
